### ISSUE TITLE
ModuleNotFoundError: No module named 'example.settings_local'

### ISSUE THREAD

**Issue by MsMansiDhruv** [presslabs/django-payu-ro#16]
I cloned the repository and installed libraries but while executing command:
`python3 manage.py migrate`
I came across this issue. Could you help me out?

Traceback (most recent call last):
  File "manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/cypher/Desktop/django-payu-ro/example/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'example.settings_local'

Steps I followed:
`git clone git://github.com/PressLabs/django-payu-ro.git`
`cd django-payu-ro/example`
`virtualenv venv`
`. venv/bin/activate`
`pip install -r requirements.txt`
`./manage.py migrate` [Command returned ModuleNotFoundError]

**Comment by bogdanpetrea** [comment]
Try renaming `settings_local.py.example` to `settings_local.py` in the nested `example` directory.
